package io.springflow.starter.config;

import io.springflow.annotations.AutoApi;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.servers.Server;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.List;

/**
 * OpenAPI/Swagger configuration for SpringFlow.
 * <p>
 * This configuration is automatically activated when:
 * <ul>
 *   <li>springdoc-openapi is on the classpath</li>
 *   <li>springflow.swagger.enabled property is true (default)</li>
 * </ul>
 * </p>
 *
 * <p>
 * The configuration sets up:
 * <ul>
 *   <li>API information from {@link SpringFlowProperties.Swagger}</li>
 *   <li>Automatic endpoint documentation with tags based on entity names</li>
 *   <li>Schema generation for entities and validation constraints</li>
 *   <li>Swagger UI at /swagger-ui.html</li>
 * </ul>
 * </p>
 */
@Configuration
@ConditionalOnClass({OpenAPI.class, AutoApi.class})
@ConditionalOnProperty(prefix = "springflow.swagger", name = "enabled", havingValue = "true", matchIfMissing = true)
public class OpenApiConfiguration {

    private static final Logger log = LoggerFactory.getLogger(OpenApiConfiguration.class);

    /**
     * Creates the main OpenAPI configuration bean.
     * <p>
     * API information is populated from {@link SpringFlowProperties.Swagger} configuration.
     * This allows users to customize the API documentation via application.yml.
     * </p>
     *
     * @param properties the SpringFlow configuration properties
     * @return configured OpenAPI instance
     */
    @Bean
    public OpenAPI springFlowOpenAPI(SpringFlowProperties properties) {
        SpringFlowProperties.Swagger swagger = properties.getSwagger();

        Info info = new Info()
                .title(swagger.getTitle())
                .description(swagger.getDescription())
                .version(swagger.getVersion());

        // Add contact information if provided
        if (swagger.getContactName() != null || swagger.getContactEmail() != null || swagger.getContactUrl() != null) {
            Contact contact = new Contact();
            if (swagger.getContactName() != null) {
                contact.setName(swagger.getContactName());
            }
            if (swagger.getContactEmail() != null) {
                contact.setEmail(swagger.getContactEmail());
            }
            if (swagger.getContactUrl() != null) {
                contact.setUrl(swagger.getContactUrl());
            }
            info.setContact(contact);
        }

        // Add license information if provided
        if (swagger.getLicenseName() != null || swagger.getLicenseUrl() != null) {
            License license = new License();
            if (swagger.getLicenseName() != null) {
                license.setName(swagger.getLicenseName());
            }
            if (swagger.getLicenseUrl() != null) {
                license.setUrl(swagger.getLicenseUrl());
            }
            info.setLicense(license);
        }

        OpenAPI openAPI = new OpenAPI().info(info);

        // Add server based on base path
        List<Server> servers = new ArrayList<>();
        Server server = new Server();
        server.setUrl(properties.getBasePath());
        server.setDescription("SpringFlow API Server");
        servers.add(server);
        openAPI.setServers(servers);

        log.info("OpenAPI documentation configured: {} v{}", swagger.getTitle(), swagger.getVersion());
        log.info("Swagger UI available at /swagger-ui.html");

        return openAPI;
    }

    /**
     * Creates a grouped API for all SpringFlow-generated endpoints.
     * <p>
     * This groups all endpoints generated by SpringFlow's @AutoApi annotation,
     * making them easy to find in the Swagger UI.
     * </p>
     *
     * @param properties the SpringFlow configuration properties
     * @return grouped OpenAPI configuration for SpringFlow endpoints
     */
    @Bean
    public GroupedOpenApi springFlowApi(SpringFlowProperties properties) {
        String basePath = properties.getBasePath();
        // Remove trailing slash if present
        if (basePath.endsWith("/")) {
            basePath = basePath.substring(0, basePath.length() - 1);
        }

        log.debug("Grouping SpringFlow API endpoints under path: {}", basePath);

        return GroupedOpenApi.builder()
                .group("springflow")
                .displayName("SpringFlow Generated APIs")
                .pathsToMatch(basePath + "/**")
                .build();
    }
}
