package io.springflow.demo.entity;

import io.springflow.annotations.AutoApi;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * Customer entity demonstrating fully custom components.
 * SpringFlow will:
 * - SKIP repository generation (CustomerRepository is custom)
 * - SKIP service generation (CustomerService is custom - NOT extending GenericCrudService)
 * - SKIP controller generation (CustomerController is custom - NOT extending GenericCrudController)
 *
 * This demonstrates complete control over all three layers.
 */
@Entity
@Table(name = "customers")
@Data
@AutoApi(
    path = "/customers",
    description = "Customer management with fully custom implementation"
)
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, length = 20)
    private String customerCode; // Auto-generated by custom service (CUST-XXXXXXXX)

    @NotBlank(message = "Company name is required")
    @Column(nullable = false, length = 200)
    private String companyName;

    @Email(message = "Email must be valid")
    @Column(length = 100)
    private String email;

    @Column(length = 20)
    private String phone;

    @Column(length = 500)
    private String address;

    @Column(length = 100)
    private String city;

    @Column(length = 50)
    private String country;

    @Column(length = 20)
    private String status; // ACTIVE, INACTIVE, SUSPENDED

    public Customer() {
        this.status = "ACTIVE";
    }

    public Customer(String companyName) {
        this();
        this.companyName = companyName;
    }

    public Customer(String companyName, String email) {
        this(companyName);
        this.email = email;
    }
}
