package io.springflow.demo.entity;

import io.springflow.annotations.AutoApi;
import jakarta.persistence.*;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Invoice entity demonstrating custom service usage.
 * SpringFlow will:
 * - GENERATE InvoiceRepository
 * - SKIP service generation (InvoiceService is custom, extends GenericCrudService)
 * - GENERATE InvoiceController
 */
@Entity
@Table(name = "invoices")
@Data
@AutoApi(
    path = "/invoices",
    description = "Invoice management with custom service for business logic"
)
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, length = 50)
    private String invoiceNumber; // Auto-generated by custom service

    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be positive")
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false)
    private LocalDateTime issueDate;

    @Column
    private LocalDateTime dueDate;

    @Column(length = 20)
    private String status; // DRAFT, ISSUED, PAID, OVERDUE, CANCELLED

    @Column(length = 500)
    private String description;

    public Invoice() {
        this.issueDate = LocalDateTime.now();
        this.status = "DRAFT";
    }

    public Invoice(BigDecimal amount) {
        this();
        this.amount = amount;
    }

    public Invoice(BigDecimal amount, String description) {
        this(amount);
        this.description = description;
    }
}
